# Generated by Django 4.0.3 on 2022-03-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correction_detection', '0003_users_delete_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
